# Generated by Django 5.1.2 on 2024-10-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_equipo_campeonato_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statjugador',
            name='asistencias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statjugador',
            name='goles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statjugador',
            name='p_jugados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statjugador',
            name='t_amarrilas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statjugador',
            name='t_rojas',
            field=models.IntegerField(default=0),
        ),
    ]
